const assert = require('node:assert/strict');
const { createMonitor } = require('../src/services/availability.service');
let snapshot = [{ id: 'esp', name: 'ESP', status: 'online' }];
let failing = false;
const events = [];
const scan = createMonitor(() => { if (failing) throw new Error('Unavailable'); return snapshot; }, (device, state) => events.push({ id: device.id, state }));
scan(); scan();
assert.equal(events.length, 0);
snapshot[0].status = 'offline';
scan(); scan();
assert.deepEqual(events, [{ id: 'esp', state: 'offline' }]);
failing = true;
assert.throws(scan);
assert.equal(events.length, 1);
failing = false;
snapshot[0].status = 'online';
scan(); scan();
assert.equal(events.length, 2);
assert.equal(events[1].state, 'online');
snapshot = [];
scan();
snapshot = [{ id: 'esp', name: 'Re-added', status: 'offline' }];
scan();
assert.equal(events.length, 2);
snapshot = [{ id: 'esp', name: 'Re-added', status: 'unknown' }];
scan();
snapshot[0].status = 'online';
scan();
assert.equal(events.length, 2);
let attempts = 0;
const retry = createMonitor(() => snapshot, () => { if (++attempts === 1) throw new Error('Write failed'); });
retry(); snapshot[0].status = 'offline';
assert.throws(retry); retry(); retry();
assert.equal(attempts, 2);
console.log('Availability transitions, deduplication, failures and re-admission tests passed');
